parameters:

    #
    # Services
    #
    elcodi.template_manager.class: Elcodi\Component\Template\Services\TemplateManager

    #
    # Commands
    #
    elcodi.templates_load_command.class: Elcodi\Component\Template\Command\TemplatesLoadCommand
    elcodi.templates_enable_command.class: Elcodi\Component\Template\Command\TemplatesEnableCommand
