services:

    #
    # Commands
    #
    elcodi.templates_load_command:
        class: %elcodi.templates_load_command.class%
        arguments:
            - @elcodi.template_manager
        tags:
            -  { name: console.command }

    elcodi.templates_enable_command:
        class: %elcodi.templates_enable_command.class%
        arguments:
            - @elcodi.manager.configuration
        tags:
            -  { name: console.command }
