services:

    #
    # Services
    #
    elcodi.template_manager:
        class: %elcodi.template_manager.class%
        arguments:
            kernel: @kernel
            configuration_manager: @elcodi.configuration_manager
